import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from './ClientWrapper';
import { Inter } from 'next/font/google';
import { Anton } from 'next/font/google';

const inter = Inter({ 
  subsets: ['latin'], 
  variable: '--font-inter' });
const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-anton',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${anton.variable} antialiased`}>

        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
